name       : flake8
version    : 3.6.0
release    : 6
source     :
    - https://files.pythonhosted.org/packages/source/f/flake8/flake8-3.6.0.tar.gz : 6a35f5b8761f45c5513e3405f110a86bea57982c3b75b766ce7b65217abe1670
license    : MIT
component  : programming.python
summary    : Python Code Format Checking
description: |
    flake8 is a python tool that glues together pep8, pyflakes, mccabe, and third-party plugins to check the style and quality of some python code.
builddeps  :
    - pkgconfig(python3)
    - mccabe
    - pycodestyle
    - pyflakes
    - pytest-runner
    - python-configparser
    - python-enum34
    - python-mock
    - python-setuptools
rundeps    :
    - mccabe
    - pycodestyle
    - pyflakes
    - python-configparser
    - python-enum34
setup      : |
    %patch -p1 < $pkgfiles/0001-Fix-build-files.patch
build      : |
    %python3_setup
    %python_setup
install    : |
    %python3_install
    for _f in $installdir/usr/bin/*; do
        mv -v $_f ${_f}3
    done
    %python_install
check      : |
    %python3_test
    %python_test
