name       : flake8
version    : 3.7.8
release    : 7
source     :
    - https://files.pythonhosted.org/packages/8d/a7/99222c9200af533c1ecb1120d99adbd1c033b57296ac5cb39d121db007a8/flake8-3.7.8.tar.gz : 19241c1cbc971b9962473e4438a2ca19749a7dd002dd1a946eaba171b4114548
license    : MIT
component  : programming.python
summary    : Python Code Format Checking
description: |
    flake8 is a python tool that glues together pep8, pyflakes, mccabe, and third-party plugins to check the style and quality of some python code.
builddeps  :
    - pkgconfig(python3)
    - mccabe
    - pycodestyle
    - pyflakes
    - pytest-runner
    - python-configparser
    - python-entrypoints
    - python-enum34
    - python-functools32
    - python-mock
    - python-setuptools
rundeps    :
    - mccabe
    - pycodestyle
    - pyflakes
    - python-entrypoints
    - python-configparser
    - python-enum34
    - python-functools32
build      : |
    %python3_setup
    %python_setup
install    : |
    %python3_install
    for _f in $installdir/usr/bin/*; do
        mv -v $_f ${_f}3
    done
    %python_install
check      : |
    %python3_test pytest3
    %python_test pytest
