name       : flake8
version    : 3.3.0
release    : 1
source     :
    - https://pypi.python.org/packages/47/64/382631de5fd8dab367bedeff6b5b55fd9a7c883daa44f4032636e2d203ca/flake8-3.3.0.tar.gz : b907a26dcf5580753d8f80f1be0ec1d5c45b719f7bac441120793d1a70b03f12
license    : MIT
component  : programming.python
summary    : Python Code Format Checking
description: |
    Python Code Format Checking
builddeps  :
    - pkgconfig(python-2.7)
    - python-mock
    - python-setuptools
    - python-pytest
    - pytest-runner
    - python-configparser
    - pyflakes
    - pycodestyle
    - python-enum34
    - mccabe
rundeps   :
    - python-configparser
    - pyflakes
    - pycodestyle
    - python-enum34
    - mccabe
setup      : |
    %python_setup
install    : |
    %python_install
check:
    python setup.py test
