name       : flake8
version    : 6.0.0
release    : 16
source     :
    - https://github.com/PyCQA/flake8/archive/refs/tags/6.0.0.tar.gz : 7541695804ccae27952318b9d6f0f82f4cab115745f6faebc10af19b58e71a01
homepage   : https://github.com/PyCQA/flake8
license    : MIT
component  : programming.python
summary    : Python Code Format Checking
description: |
    flake8 is a python tool that glues together pep8, pyflakes, mccabe, and third-party plugins to check the style and quality of some python code.
builddeps  :
    - pkgconfig(python3)
    - mccabe
    - pycodestyle
    - pyflakes
    - pytest-runner
    - python-mock
rundeps    :
    - mccabe
    - pycodestyle
    - pyflakes
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3 -v
